import {MeshAttribute} from '@wonderlandengine/api';
import {spatialPath} from '../public/workspace/annotation-protocol.js';
import {fromShared,projectPoint} from '../public/workspace/spatial.js';
import {labelUV,labelQuad} from './label-geometry.js';
const sub=(x,y)=>x.map((v,i)=>v-y[i]),cross=(x,y)=>[x[1]*y[2]-x[2]*y[1],x[2]*y[0]-x[0]*y[2],x[0]*y[1]-x[1]*y[0]],unit=x=>{const l=Math.hypot(...x)||1;return x.map(v=>v/l);};
export class NativeAnnotations{
 constructor(engine,material){this.engine=engine;this.base=material;this.items=new Map();}
 makeMesh(vertices,uv){const mesh=this.engine.meshes.create({vertexCount:vertices.length/3,indexData:Array.from({length:vertices.length/3},(_,i)=>i)});mesh.attribute(MeshAttribute.Position).set(0,new Float32Array(vertices));if(uv)mesh.attribute(MeshAttribute.TextureCoordinate)?.set(0,new Float32Array(uv));mesh.update();return mesh;}
 visual(vertices,canvas,uv){let mesh,texture,material,object;try{mesh=this.makeMesh(vertices,uv);texture=this.engine.textures.create(canvas);material=this.base.clone();material.setFlatTexture(texture);object=this.engine.scene.addObject();object.name='InstructionAnnotation';object.addComponent('mesh',{mesh,material});return {object,mesh,texture,material};}catch(error){object?.destroy();mesh?.destroy();material?.destroy();texture?.destroy();throw error;}}
 remove(id){const item=this.items.get(id);if(!item)return;for(const v of item.visuals){v.object.destroy();v.mesh.destroy();v.material.destroy();v.texture.destroy();}this.items.delete(id);}
 clear(){for(const id of [...this.items.keys()])this.remove(id);}
 set(a,calibration){const previous=this.items.get(a.id);if(previous&&previous.annotation.revision>=a.revision)return;if(!previous&&this.items.size>=64)return;const item={annotation:a,visuals:[],path:spatialPath(a),calibration:null};try{this.rebuild(item,calibration);}catch(error){for(const v of item.visuals){v.object.destroy();v.mesh.destroy();v.material.destroy();v.texture.destroy();}throw error;}this.remove(a.id);this.items.set(a.id,item);}
 rebuild(item,calibration){for(const v of item.visuals){v.object.destroy();v.mesh.destroy();v.material.destroy();v.texture.destroy();}item.visuals=[];item.calibration=calibration;const a=item.annotation,toWorld=p=>calibration?fromShared(calibration,p):p;
  if(a.kind!=='label'){const vertices=[],path=item.path.map(toWorld),n=calibration?unit(sub(fromShared(calibration,a.spatial.normal),calibration.origin)):a.spatial.normal;
   for(let i=1;i<path.length;i++){const x=path[i-1],y=path[i],dir=sub(y,x);if(Math.hypot(...dir)<.001)continue;const side=unit(cross(n,dir)).map(v=>v*.004),corners=[x.map((v,j)=>v+side[j]),x.map((v,j)=>v-side[j]),y.map((v,j)=>v+side[j]),y.map((v,j)=>v-side[j])];for(const index of [0,1,2,2,1,3,2,1,0,3,1,2])vertices.push(...corners[index]);}
   if(vertices.length){const c=document.createElement('canvas');c.width=c.height=4;c.getContext('2d').fillStyle=a.source==='ai'?'#f0655d':'#ffdb65';c.getContext('2d').fillRect(0,0,4,4);item.visuals.push(this.visual(vertices,c,Array(vertices.length/3*2).fill(0)));}
  }
  const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=a.source==='ai'?'#8b2925':'#153e37';ctx.fillRect(0,0,512,128);ctx.strokeStyle=a.source==='ai'?'#ff837b':'#ffdb65';ctx.lineWidth=5;ctx.strokeRect(3,3,506,122);ctx.fillStyle='#ffffff';const text=a.text||'檢查這裡';let size=32;ctx.font=`600 ${size}px sans-serif`;while(ctx.measureText(text).width>470&&size>18){size--;ctx.font=`600 ${size}px sans-serif`;}ctx.font=`600 ${size}px sans-serif`;const chars=Array.from(text);let line='',lines=[];for(const ch of chars){if(ctx.measureText(line+ch).width>470){lines.push(line);line=ch;}else line+=ch;}lines.push(line);ctx.fillText(lines[0]||'',20,lines.length>1?48:69);if(lines.length>1)ctx.fillText(lines[1].slice(0,45)+(lines.length>2?'…':''),20,91);const label=this.visual(Array(36).fill(0),c,labelUV);item.visuals.push(label);item.label=label;this.updateLabel(item,calibration,null);
 }
 updateLabel(item,calibration,matrix){const a=item.annotation,p=a.kind==='arrow'?a.spatial.points.at(-1):a.spatial.points[0],center=calibration?fromShared(calibration,p):p;item.label.mesh.attribute(MeshAttribute.Position).set(0,new Float32Array(labelQuad(center,matrix)));item.label.mesh.update();}
 update(calibration,pose,xr){for(const item of this.items.values()){if(item.calibration!==calibration)this.rebuild(item,calibration);for(const v of item.visuals)v.object.active=!xr||!!calibration;if(xr&&calibration)this.updateLabel(item,calibration,pose?.transform.matrix);}}
 projected(calibration,view){if(!calibration)return [];const result=[];for(const item of this.items.values()){const points=item.path.map(p=>projectPoint(fromShared(calibration,p),view.transform.inverse.matrix,view.projectionMatrix));if(points.some(p=>!p))continue;result.push({...item.annotation,kind:item.annotation.kind==='label'?'label':'line',spatial:undefined,points:points.map(p=>[p.x,p.y])});}return result;}
}
